M48
; DRILL file {KiCad 7.0.5-0} date 2024 April 21, Sunday 20:06:37
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-21T20:06:37-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X4.1498Y-1.1799
X4.1498Y-3.6945
X6.5983Y-1.1799
X6.5983Y-3.6945
T0
M30
